#!/bin/bash

restart_dir=/export/lv9/projects/dws/model_input/hotstart
restart_file=restart_201501_effective_fetch_spinup_02.in

outdir=$HOME/home/GETM_ERSEM_SETUPS/dws_500m/out/dws_500m/16x15/2015/01/


rm -f $outdir/restart.????.in

for i in `seq 0 9`;
do
  ln -s $restart_dir/$restart_file $outdir/restart.000$i.in
done
for i in `seq 10 99`;
do
  ln -s  $restart_dir/$restart_file $outdir/restart.00$i.in
done
for i in `seq 100 154`;
do
  ln -s  $restart_dir/$restart_file $outdir/restart.0$i.in
done
