#!/bin/bash

## qsub admin
##PBS -N move_files_qsub_single
##PBS -l nodes=1:ppn=1
##PBS -k oe
##PBS -q single

##BSUB -n 1
##BSUB -J move_files_grace
##BSUB -q cefas
##BSUB -o 'move_files.stdout'

#SBATCH --partition=LMEM --qos=normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=0-2:00:00
#SBATCH --mem=512MB
#SBATCH --output=/export/lv9/user/qzhan/move_files.stdout
#SBATCH --job-name="move_files"

#args=("$@")
#outdir=${args[0]}
#runid=${args[1]}

out_dir=$1
runid=$2

echo 'move_files'

echo $args
#hostname
#echo 'parallel: '$parallel

#out_dir=$1
#nodesid=$2
#runid=$3
echo "outdir: "$out_dir
#echo "nodesid: "$nodesid
echo "runid: "$runid

echo "Starting:Merging result files"
pwd=`pwd`
cd $out_dir
#pwd

#selections="3d 2d"
#selections="2d mean"
selections='2d 3d mean'
#selections='2d'
#selections='3d'
#selections=''
merge_files=1
if [ $merge_files -eq 1 ] ; then
for selection in $selections ; do
#  fname=$nodesid'_'$runid'.'$selection.*.nc
  echo $selections
  echo $selection
  fname=$runid'.'$selection.*.nc
  echo $fname
  sources=`ls $fname`
#  echo "sources: " $sources
#  goal=$nodesid'_'$runid'.'$selection.nc
  goal=$runid'.'$selection.nc
  $HOME/bin/ncmerge -M -v  $sources $goal
  wait
  if [ $? -eq 0 ]; then
     echo "    Merging of $nodesid_$runid.$selection.*.nc is succesful"
     echo "    Result in $goal"
     rm -f $sources
#     if [ $selection -eq "3d" ]; then
#       rm -f $sources
#     fi
     #echo "    Deleting of $nodesid_$runid.$selection.*.nc is done"
     echo $sources
  fi

done
fi
echo "Done:Merging result files"


