#!/bin/sh
### LAPLACE
#SBATCH --partition=normal --qos=normal
#SBATCH --nodes=4
##SBATCH --nodelist=no63,no64,no65,no66
##SBATCH --ntasks-per-node=40
#SBATCH --exclusive
#SBATCH --output=/export/lv1/user/jvandermolen/run_all.stdout
#SBATCH --job-name="run_all"

### LORENTZ
##BSUB -n 260                     # total number of cpu slots
###BSUB -n 32
##BSUB -J GETM_ERSEM_shelfwide    # Job name
##BSUB -q cefas                       # CEFAS batch queue
##BSUB -P C7522                   # project code
##BSUB -o 'run_all.stdout'
##BSUB -R 'select[ib]'            # infiniband for parallel jobs
##BSUB -R 'cu[type=ibnetwork:maxcus=2]'          # requests all nodes on same IB switch
##BSUB -R 'select[ivy]'            # Ivy Bridge nodes
##BSUB -R "span[ptile=13]"         # number of slots per node
###BSUB -x                          # reserve nodes exclusively
# call with: bsub < run_all_qsub_flex

### GRACE
##PBS -N run_all
##PBS -l nodes=1:ppn=32
##PBS -l walltime=48:00:00
##PBS -q batch
##PBS -m abe
###PBS -M johan.van.der.molen@nioz.nl
##PBS -j oe
##PBS -o run_all.stdout
##PBS -e run_all.stderr

module load clustershell/1.8

echo "run_all"
hostname

#echo ------------------------------------------------------
#echo -n 'Job is running on node '; cat $PBS_NODEFILE
#echo ------------------------------------------------------
#echo PBS: qsub is running on $PBS_O_HOST
#echo PBS: originating queue is $PBS_O_QUEUE
#echo PBS: executing queue is $PBS_QUEUE
#echo PBS: working directory is $PBS_O_WORKDIR
#echo PBS: execution mode is $PBS_ENVIRONMENT
#echo PBS: job identifier is $PBS_JOBID
#echo PBS: job name is $PBS_JOBNAME
#echo PBS: node file is $PBS_NODEFILE
#echo PBS: current home directory is $PBS_O_HOME
#echo PBS: PATH = $PBS_O_PATH
#echo ------------------------------------------------------

#JM activate these for execution through scheduler
#cd ${PBS_O_WORKDIR}
#echo "  PBS_O_WORKDIR" $PBS_O_WORKDIR
#echo "  PSB_NODEFILE" $PBS_NODEFILE
#rm new_hosts
#cat $PBS_NODEFILE | tr ' ' '\n' | sort | uniq > new_hosts

# Slurm
cd ${SLURM_SUBMIT_DIR}
echo "  SLURM_SUBMIT_DIR" $SLURM_SUBMIT_DIR
echo "  SLURM_JOB_NODELIST" $SLURM_JOB_NODELIST
rm new_hosts
export NODELIST=nodelist.txt
srun -l bash -c 'hostname' | sort | awk '{print $2}' > $NODELIST
cat $NODELIST | tr ' ' '\n' | sort | uniq > new_hosts


rm machinefile
MACHINEFILE=$HOME/bin/make_machinefile_qsub
$MACHINEFILE -i link_machinefile -o machinefile -n new_hosts
echo "after construction machinefile"
cp machinefile machinefile_keep

#export GETMDIR=/fs3/jvandermolen/GETM_ERSEM_SOURCES/standalone_getm/getm-2.2.2.uncouple
export GETMDIR=$HOME/home/getm-git/code
#export GOTMGUIDIR=/home/$USER/GOTM_SOURCES/gotm-git/gui.py

export runid=dws_200m
#cd $HOME/GETM_ERSEM_SETUPS/$runid/
cd $HOME/home/setups/$runid/


export conf=42x42   # Laplace 4 nodes 145 procs


export nprocesses=157   # for deletion loop in run.getm

run_type=4 #4

particle_tracking=0                            # process fields monthly for particle tracking
export particle_tracking=$particle_tracking

if [ "$conf" = "1p" ] ; then
  export PDSH=
else
  machines=`cat machinefile | sort | uniq | tr [:space:] , | sed -e "s/,$//"`
  export nodes=`cat machinefile | sort | uniq | tr [:space:] , | sed -e "s/,$//" | sed -e "y/n/ /" | sed -e "y/,/ /"`
  export DSH="clush -w $machines"
  export PDSH="clush -R ssh -w $machines"
  export firstnode=$firstnode
  export lastnode=$lastnode
fi

BASE_1=1
BASE_2=0 
BASE_3=0

mkdir -p log/$conf


EPOCH_START="2009-01-01 00:00:00"   # epoch_start should conform with year after base year
YEAR_BASE=2008

YEAR_START=2009
#YEAR_STOP=$YEAR_START
YEAR_STOP=2009
echo $YEAR_BASE

#months="01 02 03 04 05 06 07 08 09 10 11 12"
#months="01"
months=""
days="01"

# for the benefit of adjusting output.yaml; must fit model time step
timestep=10

#OUTDIR=/gpfs/afmcefas/johan/active_runs/out_nwes_getm/$runid/$conf
#OUTDIR=/gpfs/scratchenv/dtc13fpu/active_runs/out_nwes_getm/$runid/$conf
OUTDIR=`pwd`/out/$runid/$conf

# For flexible output, disable classical output
export save_2d=False
export save_3d=False

echo "linking bdy_2d.nc"
echo $BASE_1
if [ $BASE_1 == "1" -o $BASE_2 == "1" -o $BASE_3 == "1" ]; then
   echo "removing old link"
   rm ./bdy_2d.nc
   if [ $YEAR_BASE -ge 1965 -a $YEAR_BASE -lt 1973 ]; then
     ln -s boundary/tides.1965-01-01_1973-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 1973 -a $YEAR_BASE -lt 1981 ]; then
     ln -s boundary/tides.1973-01-01_1981-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 1981 -a $YEAR_BASE -lt 1987 ]; then
     ln -s boundary/tides.1981-01-01_1987-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 1987 -a $YEAR_BASE -lt 1994 ]; then
     ln -s boundary/tides.1986-09-31_1994-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 1994 -a $YEAR_BASE -lt 2000 ]; then
     ln -s boundary/tides.1992-09-31_2000-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 2000 -a $YEAR_BASE -lt 2008 ]; then
     ln -s boundary/tides.2000-01-01_2008-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 2008 -a $YEAR_BASE -lt 2014 ]; then
     ln -s boundary/tides.2008-01-01_2014-01-010.4.nc bdy_2d.nc
   fi
   if [ $YEAR_BASE -ge 2014 -a $YEAR_BASE -lt 2022 ]; then
     ln -s boundary/tides.2014-01-01_2022-01-010.4.nc bdy_2d.nc
   fi
fi
echo "done linking bdy_2d.nc"

if [ $BASE_1 == "1" ]; then
   export runtype=$run_type
   export hotstart=False
   export use_epoch=False 
   export metforcing=False
#   export metforcing=True
   export river_method=0
#   export An=50.
   export An=-1.
#   export bdy2d=False
#   export bdyramp_2d=-1
   export bdy2d=True
   export bdyramp_2d=181440 #60480 #8640 #28800 #8640 #4320
   export bdy3d=True       # should be true
   export temp_method=3
   export salt_method=3
   export calc_temp=True   # should be true
   export calc_salt=True   # should be true

   export save_initial=True
#   export An_method=2
#   export An_file=field_AN.nc
   export crit_depth=3.0
   export min_depth=1.0
   export clip_depth=0.1

   export out_dir=${OUTDIR-"./out"}/base_1
   export hot_dir=${OUTDIR-"./out"}/base_2
#   export out_dir2=${OUTDIR2-"./out"}/base_1
#   export col_dir=${COLDIR-"./out"}/base_1
   rm flex_out
   ln -s $out_dir flex_out

   export step_2d=2160 #8640 #8640 #28800 #28800 #240 is hourly for 15 sec time step
   export step_3d=17280 #8640 #43200

#   $PDSH "mkdir -p $out_dir $hot_dir"
   mkdir -p $out_dir $hot_dir
#   mkdir -p $col_dir

   ln -sf no_bio.inp bio.inp

   export logdir=log/$conf/base_1
   mkdir -p $logdir

   export start="$YEAR_BASE-10-01 00:00:00"
#   export stop="$YEAR_BASE-10-01 01:00:00"
   export stop="$YEAR_BASE-11-01 00:00:00"
   export ref_start_time="$YEAR_BASE-10-01 00:00:00"
   echo  "run.getm_qsub  $start   $stop  >& $logdir/log.$yy.$mm.$day"
 
   # modify output.yaml
#   sed -i '/time_start/c\  time_start: '$YEAR_BASE'-10-01 00:00:00' ./output.yaml
   basemonth='10'
   sed --follow-symlinks -i -e 's/\(time_start: \).\{7\}/\1'$YEAR_BASE'-'$basemonth'/' ./output.yaml

   ./run.getm "$start" "$stop" >& $logdir/log.base_1

#   ./run.getm "2000-10-01 00:00:00" "2000-11-01 00:00:00" >& log/$conf/log.base_1
#   ./run.getm "2000-10-01 00:00:00" "2000-10-03 00:00:00" >& log/$conf/log.base_1
fi


if [ $BASE_2 == "1" ]; then

   export runtype=$run_type
   export hotstart=True
   export use_epoch=False 
#   export metforcing=True
   export metforcing=False  # best not to start yet: causes instabilities in deep corners
   export river_method=0
#   export An=50.
   export An=-1.
   export bdy2d=True
   export bdyramp_2d=-1 #864000 #4320
#   export bdy2d=False
#   export bdy3d=False
   export bdy3d=True
   export temp_method=0
   export salt_method=0
   export calc_temp=True
   export calc_salt=True

#   export An_method=2
#   export An_file=field_AN.nc
   export crit_depth=2.25
   export min_depth=0.75
   export clip_depth=0.1
   export save_initial=False

   export out_dir=${OUTDIR-"./out"}/base_2
   export hot_dir=${OUTDIR-"./out"}/base_3
#   export out_dir2=${OUTDIR2-"./out"}/base_2
#   export col_dir=${COLDIR-"./out"}/base_2
   rm flex_out
   ln -s $out_dir flex_out

   export step_2d=8640 #5760 #2880 #240 is hourly for 15 sec time step
   export step_3d=43200 #5760 #2880

#   $PDSH "mkdir -p $out_dir $hot_dir"
   mkdir -p $out_dir $hot_dir
#   mkdir -p $col_dir

   ln -sf no_bio.inp bio.inp

   export logdir=log/$conf/base_2
   mkdir -p $logdir

   export start="$YEAR_BASE-11-01 00:00:00"
   export stop="$YEAR_BASE-12-01 00:00:00"
#   export stop="$YEAR_BASE-11-01 00:05:10"
   export ref_start_time="$YEAR_BASE-11-01 00:00:00"
   echo  "run.getm_qsub  $start   $stop  >& $logdir/log.base_2"

   # modify output.yaml
#   sed -i '/time_start/c\  time_start: '$YEAR_BASE'-11-01 00:00:00' ./output.yaml
   basemonth='11'
   sed --follow-symlinks -i -e 's/\(time_start: \).\{7\}/\1'$YEAR_BASE'-'$basemonth'/' ./output.yaml
 
   ./run.getm "$start" "$stop" >& $logdir/log.base_2

 #  ./run.getm "2000-11-01 00:00:00" "2000-12-01 00:00:00" >& log/$conf/log.base_2
fi

export runtype=$run_type
export hotstart=True
#export metforcing=False
export river_method=2
#export river_method=0
#export An=20.
export An=-1.
export bdy2d=True
export bdyramp_2d=-1
export bdyramp_3d=8640 #28800 #8640 #4320
#export bdy3d=False
export bdy3d=True
export temp_method=0
export salt_method=0

#export avhback=0.0 #1e-07 #1e-07

#export An_method=2
#export An_file=field_AN.nc

if [ $BASE_3 == "1" ]; then

   export meteo_ramp=181440   #introduce here but slowly
   export metforcing=True

   export use_epoch=False 
#export metforcing=False
#   export bdyramp_2d=4320
   export bdyramp_2d=-1
#   export An=50.
   export out_dir=${OUTDIR-"./out"}/base_3
   export hot_dir=${OUTDIR-"./out"}/$YEAR_START/01
#   export out_dir2=${OUTDIR2-"./out"}/base_3
#   export col_dir=${COLDIR-"./out"}/base_3
   rm flex_out
   ln -s $out_dir flex_out

   export step_2d=720 #240 is hourly for 15 sec time step (360 for 10 s)
   export step_3d=2880

   export crit_depth=1.5
   export min_depth=0.5
   export clip_depth=0.1

   export save_initial=False

#   $PDSH "mkdir -p $out_dir $hot_dir"
   mkdir -p $out_dir $hot_dir
#   mkdir -p $col_dir

   ln -sf no_bio.inp bio.inp

   export logdir=log/$conf/base_3
   mkdir -p $logdir

   export start="$YEAR_BASE-12-01 00:00:00"
   export stop="$YEAR_START-01-01 00:00:00"
   export ref_start_time="$YEAR_BASE-12-01 00:00:00"
   echo  "run.getm_qsub  $start   $stop  >& $logdir/log.base_3"

   # modify output.yaml
#   sed -i '/time_start/c\  time_start: '$YEAR_BASE'-12-01 00:00:00' ./output.yaml
   basemonth='12'
   sed --follow-symlinks -i -e 's/\(time_start: \).\{7\}/\1'$YEAR_BASE'-'$basemonth'/' ./output.yaml
 
   ./run.getm "$start" "$stop" >& $logdir/log.base_3

#   ./run.getm "2000-12-01 00:00:00" "2000-12-02 00:00:00" >& log/$conf/log.base_3
#   ./run.getm "2000-12-01 00:00:00" "2001-01-01 00:00:00" >& log/$conf/log.base_3
fi

# 2001 monthly runs
#years=( 2001 )
export bdyramp_3d=-1 #28800 #8640 #4320

export step_2d=60480 #360 #30 #60480  #8640 #5760 #2880 #2880 #240 is hourly for 15 sec time step
export step_3d=43200 #8640 #43200 #8640 #57600 #5760 #28800 #28800

#export metforcing=False
#KBKexport metforcing=False
export metforcing=True
export use_epoch=True 
#export save_initial=True

#export crit_depth=1.05
#export min_depth=0.35
export crit_depth=0.9
export min_depth=0.3
export clip_depth=0.1

export save_fluxes=True

#export An=25.
#export An=50.

yy=$YEAR_START
#for yy in $years ; do
while [ $yy -le $YEAR_STOP ] ; do
   echo "$yy"
   for mm in $months ; do
      echo "$mm"
      for dd in $days ; do
#         if [ $mm > "2" ]; then
#             export step_2d=120960  #720 is hourly
#         fi

         ln -sf do_bio.inp bio.inp

         hot_mm=`expr $mm + 1`

#	 if [ "$mm " -eq "01" ] ; then
#	    ln -sf getm_bio.inp.init getm_bio.inp
#         else
#	    ln -sf getm_bio.inp.hot getm_bio.inp
#         fi

	 if [ "$hot_mm " -lt "10" ] ; then
            hot_mm=0$hot_mm
         fi

	 if [ "$mm " -eq "12" ] ; then
            hot_mm=01
            hot_yy=`expr $yy + 1`
         else
            hot_yy=$yy
         fi

         export out_dir=${OUTDIR-"./out"}/$yy/$mm/
         export hot_dir=${OUTDIR-"./out"}/$hot_yy/$hot_mm/
#         export out_dir2=${OUTDIR2-"./out"}/$yy/$mm
#         export col_dir=${COLDIR-"./out"}/$yy/$mm
#         $PDSH "mkdir -p $out_dir $hot_dir"
         mkdir -p $out_dir $hot_dir
#         mkdir -p $col_dir
         rm flex_out
         ln -s $out_dir flex_out

         if [ $use_epoch == "True" ] ; then
           export start=$EPOCH_START
         else
	   export start="$yy-$mm-$dd 00:00:00"
         fi
	 export start="$yy-$mm-$dd 00:00:00"
	 export stop="$hot_yy-$hot_mm-$dd 00:00:00"
#	 export stop="$yy-$mm-$dd 23:00:00"
#	 stop="2001-04-02 00:00:00"

         export logdir=log/$conf/$yy$mm$dd
         export year=$yy
         export month=$mm
         mm_ref=01
         YBASE=`expr $YEAR_BASE + 1 `
         echo "YEARBASE: $YEAR_BASE"
         echo "YBASE: $YBASE"
         export ref_start_time="$YBASE-$mm_ref-$days 00:00:00"
#	 export ref_start_time="$yy-$mm-$dd 00:00:00"
         echo "run_all: ref_start_time: $ref_start_time"

         # modify output.yaml
         # !!!! this sets both 2d and 3d the same, so needs to be improved
#         sed -i '/time_start/c\  time_start: '$yy'-'$mm'-'$dd' 01:00:00' ./output.yaml
         sed --follow-symlinks -i -e 's/\(time_start: \).\{7\}/\1'$yy'-'$mm'/' ./output.yaml

         rm ./bdy_2d.nc
         if [ $yy -ge 1965 -a $yy -lt 1973 ]; then
           ln -s boundary/tides.1965-01-01_1973-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 1973 -a $yy -lt 1981 ]; then
           ln -s boundary/tides.1973-01-01_1981-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 1981 -a $yy -lt 1987 ]; then
           ln -s boundary/tides.1981-01-01_1987-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 1987 -a $yy -lt 1994 ]; then
           ln -s boundary/tides.1986-09-31_1994-01-010.4.nc bdy_2d.nc 
         fi
         if [ $yy -ge 1994 -a $yy -lt 2000 ]; then
           ln -s boundary/tides.1992-09-31_2000-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 2000 -a $yy -lt 2008 ]; then
           ln -s boundary/tides.2000-01-01_2008-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 2008 -a $yy -lt 2014 ]; then
           ln -s boundary/tides.2008-01-01_2014-01-010.4.nc bdy_2d.nc
         fi
         if [ $yy -ge 2014 -a $yy -lt 2022 ]; then
           ln -s boundary/tides.2014-01-01_2022-01-010.4.nc bdy_2d.nc
         fi


         mkdir -p $logdir
         ./run.getm "$start" "$stop" >& log/$conf/log.$yy.$mm.$dd
         wait
         sleep 1
#         sleep 7200

      done
      
        # particle tracking
         if [ $particle_tracking == 1 ] ; then
           export ptcol_dir=/fhgfs/client/jvandermolen/active_runs/out_nwes_getm/north_west_european_shelf/20x20/$yy
           outdirparticle=/fhgfs/client/jvandermolen/active_runs/out_nwes_getm/north_west_european_shelf/20x20/particletracking
           mkdir $outdirparticle
           echo $outdirparticle
           export ptyear=$yy
           if [ $mm == "01" ] ; then
             export ptmm1=1
           fi
           if [ $mm == "02" ] ; then
             export ptmm1=2
           fi
           if [ $mm == "03" ] ; then
             export ptmm1=3
           fi
           if [ $mm == "04" ] ; then
             export ptmm1=4
           fi
           if [ $mm == "05" ] ; then
             export ptmm1=5
           fi
           if [ $mm == "06" ] ; then
             export ptmm1=6
           fi
           if [ $mm == "07" ] ; then
             export ptmm1=7
           fi
           if [ $mm == "08" ] ; then
             export ptmm1=8
           fi
           if [ $mm == "09" ] ; then
             export ptmm1=9
           fi
           if [ $mm == "10" ] ; then
             export ptmm1=10
           fi
           if [ $mm == "11" ] ; then
             export ptmm1=11
           fi
           if [ $mm == "12" ] ; then
             export ptmm1=12
           fi
           export ptdaily_dir=$outdirparticle
           export ptfstem=$runid
           nsubs=`sed -n '1p' par_setup.dat`
           let nsubs=$nsubs-1
           export ptnsubs=$nsubs
           # merge subdomains into daily files
           ~/bin/particle_extract_perday_automatic_permonth >& $outdirparticle/err_particleextract_$yy$mm.txt
           # remove model output to make space for next year's run
           rm -f $ptcol_dir/$mm/*.nc
         fi

      
   done
   yy=`expr $yy + 1`
done

#mpdallexit
